# Project information
site_name: D&D "Palant edition"
site_description: Набор необходимых, по моему мнению, изменений, tweaks, fixes к правилам 5й редакции Подземелий и Драконов.
site_author: Антон Палихов aka Palant
# Repository
repo_name: 'palikhov/DnD_Palant_edition'
repo_url: 'https://github.com/palikhov/DnD_Palant_edition'
# trade marks and copyright

copyright: 'Copyright &copy; 2019 Palant и команда Киборгов и Чародеев'

nav:
    - Главная: index.md
    - Downtime:
            - Downtime Completed: homerules/downtime-revisited/downtime.md
            - Покупка волшебных вещей: homerules/downtime-revisited/buying-a-magic-item.md
            - Исследования: homerules/downtime-revisited/research.md
            - Создание предмета: homerules/downtime-revisited/crafting-an-item.md
            - Преступления: homerules/downtime-revisited/crime.md
            - Азартные игры: homerules/downtime-revisited/gambling.md
            - Подпольные бои: homerules/downtime-revisited/pit-fighting.md
            - Отдых-отдых-отдых: homerules/downtime-revisited/relaxation.md
            - Религиозная служба: homerules/downtime-revisited/religious-service.md
            - Написание свитка заклинаний: homerules/downtime-revisited/scribing-a-spell-scroll.md
            - Продажа волшебного предмета: homerules/downtime-revisited/selling-a-magic-item.md
            - Training: homerules/downtime-revisited/training.md
            - Work: homerules/downtime-revisited/work.md
            - Новые возможности в простое: homerules/downtime-activities.md
  #  - Правила по созданию персонажей: homerules/character-creation.md
    - Расы:
      - Шейд: homerules/races/shade.md
      - Фейри (демонфеи): homerules/races/feyri.md
    - Классы:
      - Общее: homerules/classes/index.md
      - Классы: homerules/classes/classes.md
      - Классы из Арканиса: homerules/classes/arcanis-work.md
      - Варвар: homerules/classes/barbarian.md
      - Древние колдуны: homerules/classes/elder-sorcerer.md
      - Боец (воин): homerules/classes/fighter.md
      - Мистик: homerules/classes/mystic.md
      - Паладин: homerules/classes/paladin.md
      - Рейнджер: homerules/classes/ranger-rework.md
      - Специалист (авантюрист): homerules/classes/rogue.md
      - Шаман: homerules/classes/shaman.md
      - Чародей (Sorcerer): homerules/classes/sorcerer.md
      - Волшебник (маг): homerules/classes/wizard.md
      - Колдун (Warlock): homerules/classes/warlock.md
    - Опции персонажей:
      - Боевые стили: homerules/customizing/fighting-styles.md
      - Навыки (feats): homerules/customizing/feats.md
      - Боевые маневры: homerules/customizing/combat-maneuvers.md
    - Заклинания: 
      - Зачарование предметов: homerules/spells/item-enchanting-spells.md
      - Кантрипы: homerules/spells/cantrips.md
      - 3й круг заклинаний: homerules/spells/spells-3rd-lvl.md
      - Общий список: homerules/spells/spells.md
    - Снаряжение: 
      - Снаряжение: homerules/equipment/new-equipment.md
      - Наркотики: homerules/equipment/drugs.md
      - Травы и гербализм: homerules/equipment/herbalism.md
  #   - Использование частей тел чудовищ: homerules/equipment/monster-parts-harvesting.md

  #    - Случайные встречи и погода в Серебрянных пределах: homerules/environment/hazards-weather-encounters-silver-marches.md

  #    - Расширенные правила: homerules/expanded-rules/expanded_rules.md
  #    - Бой верхом: homerules/expanded-rules/mounted-combat-expanded.md
  #    - Умение читать и писать: homerules/expanded-rules/literacy-language-expanded.md
  #  - Дополнительные правила: homerules/additional-rules/additional_rules.md
  #   - Разное: homerules/misc.md
  #   - Расширенные правила по инструментам из XGE: 
  #     - Набор алхимика: homerules/tool-proficiencies/alchemists-supplies.md
  #     - Набор травника: homerules/tool-proficiencies/herbalism-kit.md
  #     - Набор отравителя: homerules/tool-proficiencies/poisoners-kit.md
  #   - Разное: homerules/misc.md
  #   - Правила для общей кампании:
  #     - Общее: shared_campaign/index.md
  #     - Потребность в игротеке: shared_campaign/needs_organized_play.md
  #     - Правила общей кампании: shared_campaign/shared_rules.md
  #     - Фракции, известность, слава: shared_campaign\factions-renown-fame.md
  #     - Модифицированные правила трех столбов: shared_campaign\three-pillars-modified.md
  # Link as comment before release 

# Configuration
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo:
    icon: 'library_books'
  language: 'ru'
  feature:
    tabs: true
    
# Customization
extra:
  search:
    language: 'en, ru, uk'
  social:
    - type: 'github'
      link: 'https://github.com/palikhov'
    - type: 'twitter'
      link: 'https://twitter.com/AVPalikhov'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/avpalikhov'
      
# Extensions
markdown_extensions:
    - smarty
    - abbr
    - attr_list
    - def_list
    - fenced_code
    - footnotes
    - tables
    - admonition
    - meta
    - wikilinks
    - codehilite:
          guess_lang: false
    - toc:
        permalink: True
    - sane_lists
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
  #  - pymdownx.emoji:
  #        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde