# Project information
site_name: D&D Palant edition
site_description: Набор необходимых, по моему мнению, изменений, tweaks, fixes к правилам 5й редакции Подземелий и Драконов.
site_author: Антон Палихов aka Palant
# Repository
repo_name: 'palikhov/DnD_Palant_edition'
repo_url: 'https://github.com/palikhov/DnD_Palant_edition'
# trade marks and copyright

copyright: 'Copyright &copy; 2019 Palant и команда Киборгов и Чародеев'

nav:
    - Главная: index.md
    - DM Resources:  docs\homerules\dm-resources.md
    - Домашние правила:
      - Правила по созданию персонажей: dm-resources.md
      - Расы:
        - Шейд: homerules\races\shade.md
        - Фейри (демонфеи): homerules\races\feyri.md
      - Изменения системы классов и самих классов:
        - Общее: homerules/classes/index.md
        - Классы: homerules/classes/classes.md
        - Классы из Арканиса: homerules/classes/arcanis-work.md
        - Варвар: homerules/classes/barbarian.md
        - Древние колдуны: homerules/classes/elder-sorcerer.md
        - Боец (воин): homerules/classes/fighter.md
        - Мистик: homerules/classes/mystic.md
        - Паладин: homerules\classes\paladin.md
        - Рейнджер: homerules/classes/ranger-rework.md
        - Специалист (авантюрист): homerules/classes/rogue.md
        - Шаман: homerules/classes/shaman.md
        - Чародей (Sorcerer): homerules\classes\sorcerer.md
        - Волшебник (маг): homerules/classes/wizard.md
        - Колдун (Warlock): homerules\classes\warlock.md
      - Твердыни и последователи:
        - Общее: homerules/stronghold_and_followers/index.md  
        - Не бовые последователи: homerules/stronghold_and_followers/non-combat-followers.md
        - Последователи: homerules\stronghold_and_followers\followers.md
        - Рыцари: homerules\stronghold_and_followers\knights.md
        - Твердыни: homerules/stronghold_and_followers/strongholds.md
        - Твердыни по типам: homerules\stronghold_and_followers\strongholds-by-type.md
        - Злодеи: homerules/stronghold_and_followers/villains.md
        - Военное дело: homerules/stronghold_and_followers/warfare.md
      - Test: 
        - Боевые маневры: homerules/combat-maneuvers.md
        - Боевые стили: homerules/fighting-styles.md
        - Языки: homerules/languages.md
        - Навыки (feats): homerules/feats.md
        - Заклинания: 
          - Зачарование предметов: homerules\spells\item-enchanting-spells.md
          - Кантрипы: homerules\spells\cantrips.md
          - 3й круг заклинаний: homerules\spells\spells-3rd-lvl.md
          - Общий список: homerules/spells.md
        - Снаряжение: 
        - Снаряжение: homerules/equipment.md
        - Наркотики: homerules\equipment\drugs.md
        - Травы и гербализм: homerules\equipment\herbalism.md
        - Использование частей тел чудовищ: homerules\equipment\monster-parts-harvesting.md
        - Волшебные предметы: homerules/magic-items.md
          - Расширенные правила по простою из XGE:
          - Исследования: homerules\downtime-revisited\research.md
      - Новые возможности в простое: homerules\downtime-activities.md
        - Файлы:
          - Руководство игрока по Вестмаршам Коллвила: files\Collvile's Player's Guide _ GM Binder.pdf
          - Руководство по настройке персонажа в Dicecloud: files\Advanced Dicecloud Character Construction.pdf    
          - Помощник для Dicecloud: files\DiceCloud Helper.xlsx
          - Руководство Жнеца Чудовищ: files\The Monster Harvester Handbook.pdf
          - Путешествующие торговцы: files\Travelling Merchants.xlsx
# Link as comment before release 

# Configuration
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo:
    icon: 'library_books'
  language: 'ru'
  feature:
    tabs: true
    
# Customization
extra:
  search:
    language: 'en, ru, uk'
  social:
    - type: 'github'
      link: 'https://github.com/palikhov'
    - type: 'twitter'
      link: 'https://twitter.com/AVPalikhov'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/avpalikhov'

# Extensions
markdown_extensions:
    - smarty
    - abbr
    - attr_list
    - def_list
    - fenced_code
    - footnotes
    - tables
    - admonition
    - meta
    - wikilinks
    - codehilite:
          guess_lang: false
    - toc:
        permalink: True
    - sane_lists
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
  #  - pymdownx.emoji:
  #        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde